### ISSUE TITLE
Node v0.12 / io.js - Non-existent file generates "Cannot read property 'fd' of undefined" error

### ISSUE THREAD

**Issue by lovell** [soldair/node-watchfd#2]
Hi Ryan, I'm using tailfd 0.1.6 with the watchfd 0.0.14 dependency (so includes the fix for #1 that may have exposed this problem) but get the following when tailing a not-yet-existent file:

```
self.emit('unlink',self.fds[ino].fd,self.fds[ino].getData());
^
TypeError: Cannot read property 'fd' of undefined
at StatWatcher.<anonymous> (node_modules/tailfd/node_modules/watchfd/watch.js:176:41)
at emitTwo (events.js:87:13)
at StatWatcher.emit (events.js:169:7)
at StatWatcher._handle.onchange (fs.js:1282:10)
```

I've only been able to reproduce this with io.js so far and have yet to work out which [recent fs.js change](https://github.com/iojs/io.js/commits/master/lib/fs.js) may be the culprit.

Adding an `if (ino) { ... }` wrapper around the `self.emit('unlink', ...)` statement seems to fix this, but perhaps the `if(!cur.ino && prev.ino || cur.nlink === 0)` [conditional](https://github.com/soldair/node-watchfd/blob/master/watch.js#L172) should prevent it getting that far.

**Comment by lovell** [comment]
I've just spotted the [test/manual/test.js](https://github.com/soldair/node-watchfd/blob/master/test/manual/test.js) script, which works with Node.js 0.10.38 but fails with Node.js v0.12.2 (and iojs v1.8.1).
```sh
$ nvm use v0.10.38
Now using node v0.10.38
$ node test/manual/test.js
OPEN  ino: 41291431, size:7
CHANGE  ino: 41291431, size: 7 -> 7
1 ' fds being watched'
...

$ rm taco.log
$ nvm use v0.12.2
Now using node v0.12.2
$ node test/manual/test.js
.../node-watchfd/watch.js:176
        self.emit('unlink',self.fds[ino].fd,self.fds[ino].getData());
                                        ^
TypeError: Cannot read property 'fd' of undefined
    at StatWatcher.<anonymous> (.../node-watchfd/watch.js:176:41)
    at StatWatcher.emit (events.js:110:17)
    at StatWatcher._handle.onchange (fs.js:1226:10)
```
I'll attempt to prepare a patch to fix this.

**Comment by soldair** [comment]
so very long ago. sorry i never responded!

**Comment by lovell** [comment]
No worries, thanks for merging the fix.
